services:
  app:
    image: kogayushi/graphql-tips:latest
    pull_policy: never
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - prometheus
    cpus: '2.0'
    mem_limit: 4G
  prometheus:
    image: prom/prometheus:v3.1.0
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:11.5.1
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/data:/var/lib/grafana
    depends_on:
      prometheus:
        condition: service_started

volumes:
  grafana_data:
