management:
  endpoints:
    access:
      default: none
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      access: read_only
    info:
      access: read_only
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
spring:
  application:
    name: spring-for-graphql-tips-by-small-startup
  graphql:
    graphiql:
      enabled: true